version: "3" 

services: 
    app:
        build: 
            context: .
        ports: 
            - "3000:3000"
        volumes: 
            - .:/src
        command: >
            sh  -c "npm start"